'use strict';
const DATA=JSON.parse(document.getElementById('portal-data').textContent), C=DATA.course;
const docs=new Map(DATA.documents.map(x=>[x.path,x]));
const KEY='bayan-learning-portal-v2';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pair=(en,ar,tag='div')=>`<div class="pair"><${tag} class="en" lang="en" dir="ltr">${en}</${tag}><${tag} class="ar" lang="ar" dir="rtl">${ar}</${tag}></div>`;
const bi=(en,ar)=>`<span class="bi"><span class="en" lang="en" dir="ltr">${en}</span><span class="ar" lang="ar" dir="rtl">${ar}</span></span>`;
const rd=path=>'#read/'+encodeURIComponent(path);
const gh=path=>C.repository+'/blob/main/'+path.split('/').map(encodeURIComponent).join('/');
const colab=name=>'https://colab.research.google.com/github/almiyead-rgb/bayan-applied-nlp-course/blob/main/notebooks/'+encodeURIComponent(name);
const btn=(href,en,ar,extra='')=>`<a class="button ${extra}" href="${esc(href)}">${bi(esc(en),esc(ar))}</a>`;
const label=(en,ar)=>pair(esc(en),esc(ar));
const title=(en,ar)=>`<div class="section-head">${pair(`<h2>${esc(en)}</h2>`,`<h2>${esc(ar)}</h2>`)}</div>`;
let state={language:'both',gates:[],ready:[]};let storageOK=true;
try{const saved=JSON.parse(localStorage.getItem(KEY)||'null');if(saved&&typeof saved==='object'){state.language=['en','ar','both'].includes(saved.language)?saved.language:'both';state.gates=Array.isArray(saved.gates)?saved.gates.filter(n=>Number.isInteger(n)&&n>=1&&n<=4):[];state.ready=Array.isArray(saved.ready)?saved.ready.filter(n=>Number.isInteger(n)&&n>=0&&n<=3):[];}}catch{storageOK=false;}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{storageOK=false;toast('Progress is temporary in this session · التقدم مؤقت في هذه الجلسة');}}
function toast(message){const n=document.getElementById('notice');n.textContent=message;n.style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>n.style.display='none',4500);}
function setLanguage(value){state.language=['en','ar','both'].includes(value)?value:'both';document.documentElement.dataset.language=state.language;document.documentElement.lang=state.language==='en'?'en':'ar';document.querySelectorAll('.languages button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.language===state.language)));save();}
function check(id,en,ar,kind='gate'){const selected=(kind==='gate'?state.gates:state.ready).includes(id);return `<label class="check"><input type="checkbox" data-check="${kind}" data-id="${id}" ${selected?'checked':''}>${label(en,ar)}</label>`;}
function docLink(path,en,ar){return btn(rd(path),en||docs.get(path)?.title||path,ar||docs.get(path)?.title||path);}
function tabs(active=0){return `<div class="tabs">${C.days.map(d=>`<a href="#day-${d.id}" class="${d.id===active?'active':''}">${bi('Day '+d.id,'اليوم '+d.id)}</a>`).join('')}${docLink('docs/04-delivery-plan.md','Journey guide','دليل الرحلة')}</div>`;}
function caution(en,ar){return `<div class="callout warning">${pair(esc(en),esc(ar),'p')}</div>`;}
function note(en,ar){return `<div class="callout">${pair(esc(en),esc(ar),'p')}</div>`;}
function home(){const next=C.days.find(d=>!state.gates.includes(d.id));return `
<section class="hero"><div class="wrap"><p class="kicker">SDAIA ACADEMY · SDA-AIE-211 · SPECIALIST</p>
${pair(`<h1>Turn language into<br><em>understanding.</em></h1><p>Natural Language Processing with Transformers. Build Bayan, one clear step at a time—from a bilingual sentence to an evaluated NLP project.</p><div class="actions">${btn('#start','Start your journey','ابدأ رحلتك','primary')}${btn('#journey','Explore the four days','استكشف الأيام','secondary')}</div>`,`<h1>من نصٍّ نقرؤه،<br>إلى <em>معنى نبنيه.</em></h1><p>معالجة اللغة الطبيعية باستخدام المحولات. نبني «بيان» خطوة واضحة بعد أخرى؛ من جملة عربية وإنجليزية إلى مشروع نقيّمه ونفهم حدوده.</p><div class="actions">${btn('#start','Start your journey','ابدأ رحلتك','primary')}${btn('#journey','Explore the four days','استكشف الأيام','secondary')}</div>`)}
<div class="facts"><div class="fact"><b>04</b><span>Days · أيام</span></div><div class="fact"><b>24</b><span>Learning hours · ساعة تعلم</span></div><div class="fact"><b>100</b><span>Total assessment · مجموع التقييم</span></div><div class="fact"><b>01</b><span>Cumulative project · مشروع تراكمي</span></div></div>
<div class="pipeline" aria-label="Bayan learning journey"><div class="node">Text<small>النص</small></div><span class="arrow" aria-hidden="true">→</span><div class="node">Tokens<small>وحدات الترميز</small></div><span class="arrow" aria-hidden="true">→</span><div class="node">Transformer<small>المحوّل</small></div><span class="arrow" aria-hidden="true">→</span><div class="node">Tasks & search<small>المهام والبحث</small></div><span class="arrow" aria-hidden="true">→</span><div class="node">Evidence<small>الدليل</small></div></div>
<p class="micro" style="margin-top:22px">Prepared & delivered by Meaad Al-Marri · إعداد وتقديم ميعاد المري</p></div></section>
<div class="wrap"><div class="continue"><div><h2>${bi(next?'Your next step: Day '+next.id:'Your next step: review the project',next?'خطوتك التالية: اليوم '+next.id:'خطوتك التالية: مراجعة المشروع')}</h2><p>${bi('One step, one result, one piece of evidence.','خطوة واحدة، نتيجة مفهومة، ودليل تحفظه.')}</p><div class="progress-track" role="progressbar" aria-label="Personal day progress · تقدم الأيام الشخصي" aria-valuemin="0" aria-valuemax="4" aria-valuenow="${state.gates.length}"><div class="progress-fill" style="width:${state.gates.length*25}%"></div></div><p class="privacy">${bi(`${state.gates.length}/4 self-marked days; not an assessment.`,`${state.gates.length}/4 أيام معلّمة ذاتيًا؛ ليست تقييمًا.`)}</p></div>${btn(next?'#day-'+next.id:'#project','Continue learning','تابع التعلم','primary')}</div>
<section class="section" id="journey">${title('Your four-day journey','رحلتك في أربعة أيام')}<div class="grid">${C.days.map(d=>`<article class="card day-card"><div class="day-top"><span class="day-num">0${d.id}</span><span class="pill">${d.outcomes.join(' · ')}</span></div>${pair(`<h3>${esc(d.label[0])}</h3>`,`<h3>${esc(d.label[1])}</h3>`)}<div class="desc">${pair(`<p>${esc(d.question[0])}</p>`,`<p>${esc(d.question[1])}</p>`)}</div><p class="micro">${bi("Build → test → explain","ابنِ ← اختبر ← اشرح")}</p>${btn('#day-'+d.id,'Open Day '+d.id,'افتح اليوم '+d.id,'primary')}${check(d.id,'I completed the day gate','أكملت بوابة اليوم')}</article>`).join('')}</div></section>
<section class="section">${projectIntro()}${architecturePanel()}${assessmentPanel()}${presentationPreview()}${submissionNotice()}${guideCards()}${title('A clear way to learn','طريقة تعلّم واضحة')}<div class="grid three"><div class="card"><span class="pill">01 · UNDERSTAND</span>${pair('<h3>Understand before running</h3><p>Start with the question, use the analogy, then read the original lesson.</p>','<h3>افهم قبل التشغيل</h3><p>ابدأ بالسؤال، واستعن بالمثال المبسط، ثم اقرأ الدرس الأصلي.</p>')}</div><div class="card"><span class="pill">02 · BUILD</span>${pair('<h3>Build the same Bayan</h3><p>Seven labs span eight application notebooks, plus one readiness notebook. Lab 3 uses two notebooks.</p>','<h3>ابنِ بيان نفسه</h3><p>سبعة مختبرات عبر ثمانية دفاتر تطبيقية، إضافة إلى دفتر الجاهزية. يستخدم المختبر الثالث دفترين.</p>')}</div><div class="card"><span class="pill">03 · EXPLAIN</span>${pair('<h3>Explain the evidence</h3><p>A saved output is a reference, not your own measured result. Follow the original gate requirements.</p>','<h3>اشرح الدليل</h3><p>المخرج المحفوظ مرجع، وليس نتيجة قياسك أنت. اتبع متطلبات بوابة الإنجاز الأصلية.</p>')}</div></div>
${note('The same six outcomes and scientific labs; a clearer learner journey and one published 100-point assessment.','الأهداف العلمية الستة واللابات نفسها؛ مع رحلة أوضح للمتدرب وتقييم واحد معلن من 100 درجة.')}
<div class="actions">${docLink('docs/01-outcomes-map.md','Outcomes and evidence','الأهداف وأدلتها')}${docLink('docs/04-delivery-plan.md','Four-day journey','رحلة الأيام الأربعة')}${btn('#library','Find a lesson or term','ابحث عن درس أو مصطلح')}</div></section></div>`;}
function dayPage(id){
 const d=C.days.find(x=>x.id===id);if(!d)return notFound();const slug='day-0'+id;
 return `<section class="page-top"><div class="wrap"><p class="kicker">DAY 0${id} · ${d.outcomes.join(' / ')}</p>${pair(`<h1>${esc(d.label[0])}</h1><p>${esc(d.question[0])}</p>`,`<h1>${esc(d.label[1])}</h1><p>${esc(d.question[1])}</p>`)}</div></section>
 <div class="wrap">${tabs(id)}<section class="section">${label(d.intro[0],d.intro[1])}${note(d.analogy[0],d.analogy[1])}${caution(d.watch[0],d.watch[1])}<div class="actions">${docLink(slug+'/README.md','Day guide','دليل اليوم')}${docLink(slug+'/GLOSSARY.md','Glossary + pronunciation','المصطلحات والنطق')}${docLink(slug+'/REFERENCES.md','Primary references','المصادر الأولية')}</div></section>
 <section class="section">${title('What you build into Bayan today','ما الذي تبنيه في بيان اليوم؟')}${dailyArchitecture(d)}${note(d.evidence[0],d.evidence[1])}</section>
 <section class="section">${title('Understand each topic, then try it','افهم كل موضوع، ثم جرّبه')}<div class="topic-list">${d.topics.map((t,i)=>`<article class="topic-card"><span class="topic-number">0${i+1}</span><div>${pair(`<h3>${esc(t.title[0])}</h3><p>${esc(t.explanation[0])}</p>`,`<h3>${esc(t.title[1])}</h3><p>${esc(t.explanation[1])}</p>`)}<div class="topic-example">${pair(`<b>Try this</b><p>${esc(t.example[0])}</p>`,`<b>جرّب هذا</b><p>${esc(t.example[1])}</p>`)}</div></div></article>`).join('')}</div><div class="source-links">${d.lessons.map((p,i)=>`<a href="${rd(p)}">${bi('Read lesson '+(i+1),'اقرأ الدرس '+(i+1))} · ${esc(docs.get(p)?.title||p)}</a>`).join('')}</div></section>
 <section class="section"><div class="lab-block">${title('Your practical path','مسارك التطبيقي')}<div class="practice-path">${d.lab_steps.map((t,i)=>`<div class="practice-step"><span>${i+1}</span>${label(t[0],t[1])}</div>`).join('')}</div>
 <div class="resources">${d.notebooks.map(n=>`<div class="resource"><div><div class="name">Notebook ${esc(n.slice(0,2))}</div><div class="file">${esc(n)}</div></div><div class="actions">${btn(colab(n),'Open assigned notebook','افتح الدفتر المطلوب','primary')}${btn(gh('notebooks/'+n),'Reference outputs','مخرجات مرجعية')}</div></div>`).join('')}</div>
 ${note('Save your own copy, run it, then save your actual outputs and changes to your repository. The reference button opens the instructor source, not your submission.','احفظ نسختك وشغّلها ثم احفظ نتائجك وتغييراتك في مستودعك. زر المرجع يفتح مصدر المدربة، لا تسليمك الشخصي.')}
 <div class="actions">${docLink('docs/learner-workflow.md','How to run and save','كيف تشغّل وتحفظ')}${docLink(d.gate,'Gate '+d.gate_name+' evidence','أدلة البوابة '+d.gate_name)}${docLink('docs/setup/troubleshooting.md','Recover from an error','حل الخطأ')}</div>${check(d.id,'I checked the day gate and saved my own evidence','راجعت بوابة اليوم وحفظت أدلتي الشخصية')}</div></section>
 <section class="section">${title('Know your data','افهم بياناتك')}<div class="resources">${d.datasets.length?d.datasets.map(p=>`<div class="resource"><div class="file">${esc(p)}</div>${btn(gh(p),'Inspect data','استعرض البيانات')}</div>`).join(''):label('Use the existing project artifact and frozen workload; no new dataset.','استخدم ناتج المشروع وعبء العمل المجمد؛ لا توجد بيانات جديدة.')}</div>${docLink('data/DATA_CARD.md','Data card','بطاقة البيانات')}
 <details class="quiz"><summary>${bi('Check your understanding · not graded','تحقق من فهمك · دون درجات')}</summary>${label(d.check[0],d.check[1])}<details><summary>${bi('Reveal explanation','أظهر التفسير')}</summary>${label(d.answer[0],d.answer[1])}</details></details>
 <div class="actions">${btn(id>1?'#day-'+(id-1):'#start','Previous step','الخطوة السابقة')}${btn(id<4?'#day-'+(id+1):'#project',id<4?'Next day':'Project and final hand-in',id<4?'اليوم التالي':'المشروع والتسليم النهائي','primary')}</div></section></div>`;
}
function startPage(){const steps=[['Prepare your Google and GitHub accounts','جهّز حسابي Google وGitHub'],['Check SDA-AIE-112 or equivalent Python/ML foundations','تحقق من SDA-AIE-112 أو ما يعادله في Python وتعلم الآلة'],['Save your notebook copies and run Runtime Doctor','احفظ نسخ دفاترك وشغّل فاحص البيئة'],['Read the data card, privacy rules and project requirements','اقرأ بطاقة البيانات والخصوصية ومتطلبات المشروع']];return `<section class="page-top"><div class="wrap">${pair('<h1>A calm first step.</h1><p><a href="#read/docs%2Flearner-workflow.md">Open the step-by-step Colab and GitHub guide →</a></p><p>You do not need to know every term yet. Prepare your workspace, follow Core, and keep the recovery guide close.</p>','<h1>بداية هادئة وواضحة.</h1><p><a href="#read/docs%2Flearner-workflow.md">افتح خطوات Colab وGitHub من البداية ←</a></p><p>لا تحتاج إلى معرفة كل مصطلح الآن. جهّز مساحة عملك، واتبع المسار الأساسي، واحتفظ بدليل الاستعادة قريبًا.</p>')}</div></section><div class="wrap"><section class="section"><div class="grid two"><div class="card"><h2>${bi('Before Day 1','قبل اليوم الأول')}</h2>${steps.map((s,i)=>check(i,s[0],s[1],'ready')).join('')}<p class="privacy">${bi('These checks are personal reminders, not verified admission or attendance.','هذه علامات تذكير شخصية، وليست تحققًا من القبول أو الحضور.')}</p>${btn(colab('00_runtime_doctor.ipynb'),'Open Runtime Doctor','افتح فاحص البيئة','primary')}</div><div class="card"><h2>${bi('Your minimum setup','تجهيزك الأساسي')}</h2>${pair('<p>Google Colab Free + GitHub. Use the existing CPU fallback; a GPU or paid API is not a course requirement. Follow the original environment instructions.</p>','<p>Google Colab المجاني وGitHub. استخدم بديل CPU الموثق؛ لا يُشترط GPU أو API مدفوع. اتبع تعليمات البيئة الأصلية.</p>')}<div class="actions">${docLink('START_HERE.md','Start-here guide','دليل البداية')}${docLink('docs/setup/README.md','Setup hub','تجهيز البيئة')}${docLink('docs/tools/free-tools.md','Free tools','الأدوات المجانية')}</div></div></div>${note('Use small synthetic course data only. Never publish personal information, credentials or API keys.','استخدم بيانات الدورة الاصطناعية الصغيرة فقط. لا تنشر معلومات شخصية أو ملفات اعتماد أو مفاتيح API.')}<div class="actions">${docLink('docs/policies/integrity-and-privacy.md','Privacy and integrity','الخصوصية والنزاهة')}${docLink('docs/03-capstone-spec.md','Know the final project','تعرّف على المشروع النهائي')}${btn('#day-1','Begin Day 1','ابدأ اليوم الأول','primary')}</div></section></div>`;}
function library(){return `<section class="page-top"><div class="wrap">${pair('<h1>Your learning library.</h1><p>Search the original lessons, glossaries, policies and guides. Source text is preserved; the language switch controls the interface and paired learning summaries.</p>','<h1>مكتبتك التعليمية.</h1><p>ابحث في الدروس والقواميس والسياسات والأدلة الأصلية. النص المرجعي محفوظ بلغته؛ ومفتاح اللغة يغيّر الواجهة والملخصات الثنائية.</p>')}</div></section><div class="wrap"><section class="section"><div class="search-box"><input id="search" type="search" aria-label="Search lessons · ابحث في الدروس" placeholder="Attention, NER, الانتباه، التسليم…" autocomplete="off"><select id="category" aria-label="Filter library · تصفية المكتبة"><option value="">All resources · كل الموارد</option value="day-01/">Day 1 · اليوم الأول</option><option value="day-02/">Day 2 · اليوم الثاني</option><option value="day-03/">Day 3 · اليوم الثالث</option><option value="day-04/">Day 4 · اليوم الرابع</option><option value="GLOSSARY.md">Glossaries · القواميس</option><option value="assessments/">Assessment · التقييم</option><option value="docs/">Guides · الأدلة</option></select></div><p id="search-count" class="privacy" role="status" aria-live="polite"></p><div id="search-results" class="library-list"></div></section></div>`;}
const norm=s=>String(s).toLowerCase().normalize('NFKC').replace(/[\u064B-\u065F\u0670\u0640]/g,'').replace(/[أإآ]/g,'ا');
function updateSearch(){const q=norm(document.getElementById('search').value.trim()),cat=document.getElementById('category').value;let found=DATA.documents.filter(d=>(!cat||d.path.includes(cat))&&(!q||norm(d.search).includes(q)));found.sort((a,b)=>(norm(b.title).includes(q)?1:0)-(norm(a.title).includes(q)?1:0));document.getElementById('search-count').textContent=found.length+' resources · مورد';document.getElementById('search-results').innerHTML=found.length?found.map(d=>`<a href="${rd(d.path)}"><b dir="auto">${esc(d.title)}</b><small>${esc(d.path)}</small></a>`).join(''):`<div class="empty">${label('No match. Try a shorter Arabic or English term.','لا توجد نتيجة. جرّب مصطلحًا أقصر بالعربية أو الإنجليزية.')}</div>`;}
function readPage(path){const d=docs.get(path);if(!d)return notFound();const group=/^day-0([1-4])\//.exec(path);const related=group?DATA.documents.filter(x=>x.path.startsWith('day-0'+group[1]+'/')):DATA.documents.filter(x=>x.path.startsWith('docs/')&&x.path.endsWith('.md')).slice(0,18);return `<div class="wrap">${tabs(group?Number(group[1]):0)}<section class="section"><div class="reader-layout"><aside class="reader-sidebar"><h2>${bi('On this page','في هذه الصفحة')}</h2>${d.headings.slice(0,24).map(h=>`<a class="toc-link" href="${rd(path)}?anchor=${encodeURIComponent(h.id)}" dir="auto">${esc(h.text)}</a>`).join('')}<hr><h2>${bi('Related resources','موارد قريبة')}</h2>${related.map(r=>`<a href="${rd(r.path)}" dir="auto">${esc(r.title)}</a>`).join('')}</aside><article class="reader"><div class="reader-tools">${btn(gh(path),'View the source on GitHub','اعرض المصدر في GitHub')}<button id="print">Print · طباعة</button><button id="font" aria-pressed="false">A+ · تكبير</button>${btn('#library','Library','المكتبة')}</div><div class="source-tag">${esc(path)}<br>${bi('Original reference text. No automatic translation or hidden rewriting.','النص المرجعي الأصلي؛ دون ترجمة آلية أو إعادة كتابة خفية.')}</div><div class="markdown" id="reference-content">${d.html}</div><div class="reading-end">${btn(group?'#day-'+group[1]:'#library','Back to the learning path','العودة لمسار التعلم','primary')}</div></article></div></section></div>`;}
function dailyArchitecture(d){return `<ol class="architecture-flow" aria-label="Day ${d.id} architecture">${d.architecture.map(t=>`<li>${label(esc(t[0]),esc(t[1]))}</li>`).join('')}</ol>`;}
function projectIntro(){return `<section class="project-intro">${title('Bayan: the scenario you are building','بيان: السيناريو الذي تبنيه')}${pair('<p>A fictional service-support team receives feedback in Arabic and English. It needs topics, sentiment, entities, source-supported answers and similar historical cases—in one inspectable response.</p>','<p>يستقبل فريق دعم لخدمات افتراضية ملاحظات بالعربية والإنجليزية. يحتاج الموضوع والمشاعر والكيانات وإجابة يسندها النص وحالات سابقة متشابهة، ضمن استجابة واحدة يمكن فحصها.</p>')}
<div class="example-message">${pair('<b>Follow one synthetic message</b><p>“My permit renewal in Riyadh has been delayed. When will it be completed?”</p>','<b>تتبّع ملاحظة اصطناعية واحدة</b><p>«تأخر تجديد التصريح في الرياض. متى يكتمل؟»</p>')}</div>${label('Classify the message, extract supported entities, search similar cases and answer only when the supplied context supports the answer. The example is not a measured output to copy.','صنّف الملاحظة، واستخرج الكيانات المدعومة، وابحث عن حالات مشابهة، وأجب فقط عندما يدعم السياق الإجابة. المثال ليس مخرجًا مقاسًا للنسخ.')}
<div class="actions">${docLink('docs/project-walkthrough.md','Full scenario + repository structure','السيناريو وهيكل المستودع')}${docLink('docs/03-capstone-spec.md','Scientific requirements','المتطلبات العلمية')}</div></section>`;}
function architecturePanel(){return `<section class="architecture-panel">${title('The project architecture','معمارية المشروع')}<div class="architecture-box">
<div class="architecture-node">${label('Synthetic Arabic / English input','مدخل عربي / إنجليزي اصطناعي')}</div><div class="flow-down" aria-hidden="true">↓</div>
<div class="architecture-node highlight">${label('Privacy + safe display copy + versioned model text','حماية + نسخة عرض آمنة + نص نموذج ذو إصدار')}</div><div class="flow-down" aria-hidden="true">↓</div>
<div class="architecture-branches"><div class="architecture-branch">${pair('<h3>Task models</h3><p>Topic + sentiment<br>NER<br>Extractive QA</p><small>QA also needs a question and supplied context.</small>','<h3>نماذج المهام</h3><p>الموضوع + المشاعر<br>الكيانات المسماة<br>الأسئلة الاستخراجية</p><small>تحتاج الأسئلة أيضًا سؤالًا وسياقًا مقدمًا.</small>')}</div><div class="architecture-branch">${pair('<h3>Semantic search</h3><p>Sentence vectors + L2<br>FAISS retrieval<br>Cross-encoder re-ranking</p>','<h3>البحث الدلالي</h3><p>متجهات الجمل + L2<br>استرجاع FAISS<br>إعادة ترتيب بالمشفر المشترك</p>')}</div></div>
<div class="flow-down" aria-hidden="true">↓</div><div class="architecture-node highlight">${label('Unified response → tested API / TestClient','استجابة موحدة ← خدمة مختبرة / TestClient')}</div>
<div class="architecture-assurance">${label('Across every component: evaluation, error analysis, versioning, privacy and measured performance.','عبر جميع المكونات: التقييم وتحليل الأخطاء والإصدارات والخصوصية وقياس الأداء.')}</div></div>
${label('Train and prepare the index outside the request path. Inference uses those saved components; the website itself does not run the ML models.','يجري التدريب وتجهيز الفهرس خارج مسار الطلب. يستخدم الاستدلال المكونات المحفوظة؛ موقع الدورة نفسه لا يشغّل نماذج تعلم الآلة.')}</section>`;}
function assessmentPanel(){return `<section class="assessment-panel" id="assessment">${title('Know exactly how you are assessed','اعرف بدقة كيف ستُقيّم')}<div class="score-grid new-scores">${[['Technical','تقنية',70],['Administrative','إدارية',20],['Presentation','العرض',10]].map(x=>`<div class="score"><b>${x[2]} / 100</b>${label(x[0],x[1])}</div>`).join('')}</div>
${note('100 points in total. The 10 presentation points are included. Practice quizzes have no separate weighting.','المجموع 100 درجة. عشر درجات العرض ضمنها. الاختبارات التدريبية دون وزن مستقل.')}
${['technical','administrative','presentation'].map((cat,i)=>`<details class="rubric-detail"><summary>${bi(['Technical requirements · 70','Administrative requirements · 20','Presentation requirements · 10'][i],['المتطلبات التقنية · 70','المتطلبات الإدارية · 20','متطلبات العرض · 10'][i])}</summary><div class="rubric-rows">${C.rubric.filter(x=>x.category===cat).map(x=>`<article class="rubric-row"><div class="rubric-id">${x.id}<b>${x.points}</b></div><div>${pair(`<h3>${esc(x.title[0])}</h3>`,`<h3>${esc(x.title[1])}</h3>`)}${x.items.map(t=>`<div class="criterion">${pair(`<span>${t.points} pts</span> ${esc(t.text[0])}`,`<span>${t.points} درجات</span> ${esc(t.text[1])}`)}</div>`).join('')}<p class="evidence-path">${esc(x.evidence)}</p></div></article>`).join('')}</div></details>`).join('')}
<div class="actions">${docLink('docs/policies/assessment-and-completion.md','Full rubric and partial credit','السلم الكامل وآلية منح النقاط')}${docLink('docs/presentation-guide.md','Five-part individual presentation','مواصفات العرض الفردي')}</div></section>`;}
function submissionNotice(){return `<section class="one-shot">${pair('<h2>Submit once. Check thoroughly first.</h2><p>Your final submitted commit is graded once. No edited replacement is accepted after hand-in. Check and improve freely before you send it.</p>','<h2>أرسل مرة واحدة، بعد مراجعة كاملة.</h2><p>تُصحّح نسخة الـCommit المسلّمة مرة واحدة. لا تُقبل نسخة معدلة بعد الإرسال. افحص وحسّن عملك قبل أن ترسله.</p>')}${pair('<p>The starter is allowed; passing off the instructor’s notebook or copied results as your own is not. Review includes source/output comparison and individual explanation; a similarity percentage alone does not prove misconduct.</p>','<p>استخدام قالب البداية مسموح؛ أما نسبة دفتر المدربة أو النتائج المنسوخة إلى نفسك فغير مسموح. تتضمن المراجعة مقارنة المصدر والمخرجات والتحقق من فهمك الفردي؛ نسبة التشابه وحدها ليست حكمًا بالغش.</p>')}<div class="actions">${docLink('docs/pre-submission-checklist.md','Review before sending','راجع قبل الإرسال')}${docLink('docs/policies/integrity-and-privacy.md','Integrity and permitted reuse','النزاهة والاستخدام المسموح')}</div></section>`;}
function guideCards(){return `<section class="section">${title('From your own Colab to your own GitHub','من Colab الخاص بك إلى GitHub الخاص بك')}<div class="grid three">${[
['01','Create and run','أنشئ وشغّل','Understand cells and Runtime. Save your own copy, run top to bottom and keep your own outputs.','افهم الخلايا وRuntime. احفظ نسختك وشغّلها بالترتيب واحتفظ بمخرجاتك.','docs/learner-workflow.md'],
['02','Document and attribute','وثّق وانسب','Save notebooks and separate runtime files; explain the project in README and credit the Academy and sources.','احفظ الدفاتر وملفات الجلسة المنفصلة؛ واشرح مشروعك في README وانسب الأكاديمية والمصادر.','docs/learner-workflow.md'],
['03','Verify and freeze','افحص وثبّت','Run tests and preflight, inspect links, create submission-v1.0 and send its exact commit SHA.','شغّل الاختبارات والفحص المسبق وافحص الروابط وأنشئ submission-v1.0 وأرسل بصمة نسخته.','docs/policies/submission.md']
].map(x=>`<article class="card"><span class="pill">${x[0]}</span>${pair(`<h3>${x[1]}</h3><p>${x[3]}</p>`,`<h3>${x[2]}</h3><p>${x[4]}</p>`)}${docLink(x[5],'Step-by-step guide','الخطوات بالتفصيل')}</article>`).join('')}</div></section>`;}
function presentationPreview(){return `<section class="section">${title('Your presentation: five parts, ten points','عرضك: خمسة أقسام وعشر درجات')}${label('Prepare a five-minute walkthrough plus two minutes of individual verification, with up to five slides or equivalent.','جهّز عرضًا من خمس دقائق ودقيقتين للتحقق الفردي، بخمس شرائح كحد أقصى أو ما يعادلها.')}<ol class="presentation-flow">${[['Problem + user','المشكلة والمستخدم'],['Architecture + choices','المعمارية والاختيارات'],['Own AR/EN demo + boundary case','تطبيقك بالعربية والإنجليزية وحالة حدية'],['Quality + performance evidence','دليل الجودة والأداء'],['Limitation + measured extension','قيد معروف وامتداد مقاس']].map(t=>`<li>${label(t[0],t[1])}</li>`).join('')}</ol>${docLink('docs/presentation-guide.md','Exact presentation requirements','متطلبات العرض التفصيلية')}</section>`;}
function project(){return `<section class="page-top"><div class="wrap">${pair('<h1>Your project, from scenario to submission.</h1><p>One cumulative Bayan. Your own execution, clear evidence and one final assessment.</p>','<h1>مشروعك، من السيناريو إلى التسليم.</h1><p>بيان واحد يتدرّج معك. تنفيذك الشخصي وأدلة واضحة وتقييم نهائي واحد.</p>')}</div></section><div class="wrap"><div class="section">${projectIntro()}${architecturePanel()}${assessmentPanel()}${presentationPreview()}${submissionNotice()}${guideCards()}
<section class="section">${title('Your final file structure','هيكل ملفاتك النهائي')}<div class="markdown">${docs.get('docs/project-walkthrough.md')?.html.match(/<pre>[\s\S]*?<\/pre>/g)?.find(x=>x.includes('bayan-nlp-YOUR_USERNAME'))||'<p>Open the structure guide below.</p>'}</div>${docLink('docs/project-walkthrough.md','Structure and component roles','الهيكل ووظيفة المكونات')}</section>${linkBuilder()}${selfReview()}</div></div>`;}
function linkBuilder(){return `<section class="section"><div class="card"><h2>${bi('Build your own Colab links','أنشئ روابط Colab الخاصة بمشروعك')}</h2>${label('Enter your public repository URL. This only formats links in your browser; it does not connect to your account or upload anything.','أدخل رابط مستودعك العام. تنسق الأداة الروابط في متصفحك فقط؛ لا تتصل بحسابك ولا ترفع شيئًا.')}<label for="learner-repo">GitHub repository URL · رابط المستودع</label><div class="link-builder"><input id="learner-repo" type="url" dir="ltr" placeholder="https://github.com/username/bayan-nlp-username"><button id="make-links" type="button">Generate · إنشاء</button></div><p id="link-feedback" role="status"></p><pre id="learner-links" tabindex="0" hidden></pre><button id="copy-links" type="button" hidden>Copy Markdown · نسخ Markdown</button></div></section>`;}
function selfReview(){const items=[['I reviewed all T1–T7 technical evidence','راجعت أدلة التقنية T1–T7'],['I completed A1–A5 and checked public links','أكملت الإدارية A1–A5 وفحصت الروابط'],['I ran tests and the two validators; I inspected outputs','شغلت الاختبارات والفاحصين وراجعت المخرجات'],['I prepared P1–P5 and can explain my own work','جهزت العرض P1–P5 وأستطيع شرح عملي'],['I removed secrets and checked the final tag/SHA','أزلت الأسرار وفحصت الوسم والبصمة النهائية'],['I understand: one final assessment, no replacement after sending','أفهم أن التصحيح مرة واحدة ولا استبدال بعد الإرسال']];return `<section class="section"><div class="card"><h2>${bi('Pause before you send','توقف للمراجعة قبل الإرسال')}</h2><p class="privacy">${bi('Session-only self-check. It neither inspects files nor sends your submission.','قائمة ذاتية لهذه الجلسة؛ لا تفحص الملفات ولا ترسل المشروع.')}</p>${items.map((t,i)=>`<label class="check final-check"><input type="checkbox" data-final-check="${i}">${label(t[0],t[1])}</label>`).join('')}<p id="review-status" role="status">0 / 6 · Self-review only · مراجعة ذاتية فقط</p>${docLink('docs/pre-submission-checklist.md','Full evidence checklist','قائمة الأدلة الكاملة')}${docLink('docs/policies/submission.md','Final hand-in instructions','تعليمات الإرسال النهائي')}</div></section>`;}
function help(){return `<section class="page-top"><div class="wrap">${pair('<h1>A problem is a checkpoint, not a dead end.</h1>','<h1>المشكلة نقطة فحص، وليست نهاية الطريق.</h1>')}</div></section><div class="wrap"><section class="section"><div class="grid two"><div class="card"><h2>${bi('Recover your workflow','استعد سير عملك')}</h2>${pair('<p>Save your work, read the first error and follow the source troubleshooting guide. Do not invent outputs or skip Core to look finished.</p>','<p>احفظ عملك، واقرأ أول خطأ، واتبع دليل الأعطال الأصلي. لا تختلق مخرجات أو تتجاوز المتطلبات الأساسية ليبدو العمل مكتملًا.</p>')}<div class="actions">${docLink('docs/setup/troubleshooting.md','Troubleshooting','حل الأعطال')}${docLink('docs/setup/colab.md','Colab guide','دليل كولاب')}${docLink('docs/setup/github.md','GitHub guide','دليل GitHub')}</div></div><div class="card"><h2>${bi('Your personal progress','تقدمك الشخصي')}</h2>${pair('<p>Checkmarks are stored in this browser only. They are not sent to the instructor. Export a personal backup or reset the checkmarks on this device.</p>','<p>تُحفظ العلامات في هذا المتصفح فقط ولا ترسل إلى المدربة. يمكنك تصدير نسخة شخصية أو تصفير العلامات على هذا الجهاز.</p>')}<div class="actions"><button id="export-progress">Export progress · تصدير التقدم</button><button id="reset-progress">Reset progress · تصفير التقدم</button></div><p class="privacy">${storageOK?'Local browser storage · تخزين محلي في المتصفح':'Temporary session only · حفظ مؤقت في الجلسة فقط'}</p></div></div><div class="actions">${docLink('docs/04-delivery-plan.md','Journey and recovery','الرحلة والاستعادة')}${docLink('docs/01-outcomes-map.md','What counts as evidence?','ما الذي يُعد دليلًا؟')}${btn('#start','Return to readiness','العودة للجاهزية','primary')}</div></section></div>`;}
function notFound(){return `<div class="wrap"><section class="section"><div class="empty"><h1>Page not found · الصفحة غير موجودة</h1><p>Use the course library to find the original resource.</p><p dir="rtl">استخدم مكتبة الدورة للوصول إلى المورد الأصلي.</p>${btn('#library','Open library','افتح المكتبة','primary')}</div></section></div>`;}
function bindContent(){
 document.querySelectorAll('[data-final-check]').forEach(n=>n.addEventListener('change',()=>{const done=document.querySelectorAll('[data-final-check]:checked').length;document.getElementById('review-status').textContent=`${done} / 6 · ${done===6?'Self-review completed, not a grade or submission · اكتملت المراجعة الذاتية، وليست درجة أو إرسالًا':'Self-review only · مراجعة ذاتية فقط'}`;}));
 document.getElementById('make-links')?.addEventListener('click',()=>{const v=document.getElementById('learner-repo').value.trim().replace(/\/$/,'');const match=v.match(/^https:\/\/github\.com\/([A-Za-z0-9_-]+)\/([A-Za-z0-9_.-]+)$/);const output=document.getElementById('learner-links'),feedback=document.getElementById('link-feedback'),copy=document.getElementById('copy-links');if(!match||v===C.repository){feedback.textContent='Use your own repository URL, not the instructor or a local file. · أدخل رابط مستودعك، لا رابط المدربة أو ملف محلي.';output.hidden=true;copy.hidden=true;return;}const names=['00_runtime_doctor.ipynb',...C.days.flatMap(d=>d.notebooks)];output.textContent='| Notebook | Open in Colab |\n|---|---|\n'+names.map(n=>`| ${n} | [Open in Colab](https://colab.research.google.com/github/${match[1]}/${match[2]}/blob/main/notebooks/${n}) |`).join('\n');output.hidden=false;copy.hidden=false;feedback.textContent='Links formatted only. Upload the files and verify access before hand-in. · نُسّقت الروابط فقط؛ ارفع الملفات وافحص الوصول قبل التسليم.';});
 document.getElementById('copy-links')?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(document.getElementById('learner-links').textContent);toast('Copied Markdown · تم نسخ Markdown');}catch{toast('Select the text and copy manually · حدد النص وانسخه يدويًا');}});
document.querySelectorAll('[data-check]').forEach(n=>n.addEventListener('change',()=>{const id=Number(n.dataset.id),key=n.dataset.check==='gate'?'gates':'ready';state[key]=n.checked?[...new Set([...state[key],id])]:state[key].filter(x=>x!==id);save();const bar=document.querySelector('[role=progressbar]');if(bar){bar.setAttribute('aria-valuenow',state.gates.length);bar.firstElementChild.style.width=state.gates.length*25+'%';}if(key==='gates'&&['','#home','#journey'].includes(location.hash)){const y=window.scrollY;render();requestAnimationFrame(()=>window.scrollTo(0,y));}toast('Personal progress updated · تم تحديث تقدمك الشخصي');}));
const search=document.getElementById('search');if(search){search.addEventListener('input',updateSearch);document.getElementById('category').addEventListener('change',updateSearch);updateSearch();}
document.getElementById('print')?.addEventListener('click',()=>window.print());document.getElementById('font')?.addEventListener('click',e=>{const on=document.querySelector('.reader').classList.toggle('large');e.currentTarget.setAttribute('aria-pressed',String(on));});
document.querySelectorAll('.markdown pre').forEach(pre=>{const b=document.createElement('button');b.className='copy-code';b.textContent='Copy · نسخ';b.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(pre.querySelector('code')?.textContent||'');toast('Code copied · نُسخ الكود');}catch{toast('Select the code and copy manually · حدد الكود وانسخه يدويًا');}});pre.appendChild(b);});
document.getElementById('export-progress')?.addEventListener('click',()=>{const blob=new Blob([JSON.stringify({course:C.id,version:C.version,saved_at:new Date().toISOString(),...state},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='bayan-personal-progress.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
document.getElementById('reset-progress')?.addEventListener('click',()=>{if(window.confirm('Reset personal progress on this browser? This does not change grades.\nهل تصفّر تقدمك الشخصي في هذا المتصفح؟ لا يتغير أي تقييم.')){state.gates=[];state.ready=[];save();render();toast('Personal progress reset · صُفّر التقدم الشخصي');}});}
function render(){let hash;try{hash=decodeURIComponent(location.hash.slice(1));}catch{hash='invalid';}const [route,params]=hash.split('?');let html;if(!route||route==='home'||route==='journey')html=home();else if(/^day-[1-4]$/.test(route))html=dayPage(Number(route.slice(-1)));else if(route==='start')html=startPage();else if(route==='library')html=library();else if(route==='project')html=project();else if(route==='help')html=help();else if(route.startsWith('read/'))html=readPage(route.slice(5));else html=notFound();document.getElementById('main').innerHTML=html;bindContent();document.title=(route.startsWith('read/')?(docs.get(route.slice(5))?.title||'Bayan'):'بيان | Bayan — Applied NLP')+' · Meaad Al-Marri';const anchor=new URLSearchParams(params||'').get('anchor');requestAnimationFrame(()=>{if(anchor){const target=document.getElementById(anchor);if(target)target.scrollIntoView();else window.scrollTo(0,0);}else if(route==='journey')document.getElementById('journey')?.scrollIntoView();else window.scrollTo(0,0);});}
document.querySelectorAll('.languages button').forEach(b=>b.addEventListener('click',()=>setLanguage(b.dataset.language)));
window.addEventListener('hashchange',()=>{render();document.getElementById('main').focus({preventScroll:true});});
setLanguage(state.language);render();
