'use strict';
const DATA=JSON.parse(document.getElementById('portal-data').textContent), C=DATA.course;
const docs=new Map(DATA.documents.map(x=>[x.path,x]));
const KEY='bayan-learning-portal-v2';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pair=(en,ar,tag='div')=>`<div class="pair"><${tag} class="en" lang="en" dir="ltr">${en}</${tag}><${tag} class="ar" lang="ar" dir="rtl">${ar}</${tag}></div>`;
const bi=(en,ar)=>`<span class="bi"><span class="en" lang="en" dir="ltr">${en}</span><span class="ar" lang="ar" dir="rtl">${ar}</span></span>`;
const rd=path=>'#read/'+encodeURIComponent(path);
const gh=path=>C.repository+'/blob/main/'+path.split('/').map(encodeURIComponent).join('/');
const colab=name=>'https://colab.research.google.com/github/almiyead-rgb/bayan-applied-nlp-course/blob/main/notebooks/'+encodeURIComponent(name);
const btn=(href,en,ar,extra='')=>`<a class="button ${extra}" href="${esc(href)}">${bi(esc(en),esc(ar))}</a>`;
const label=(en,ar)=>pair(esc(en),esc(ar));
const title=(en,ar)=>`<div class="section-head">${pair(`<h2>${esc(en)}</h2>`,`<h2>${esc(ar)}</h2>`)}</div>`;
let state={language:'both',gates:[],ready:[]};let storageOK=true;
try{const saved=JSON.parse(localStorage.getItem(KEY)||'null');if(saved&&typeof saved==='object'){state.language=['en','ar','both'].includes(saved.language)?saved.language:'both';state.gates=Array.isArray(saved.gates)?saved.gates.filter(n=>Number.isInteger(n)&&n>=1&&n<=4):[];state.ready=Array.isArray(saved.ready)?saved.ready.filter(n=>Number.isInteger(n)&&n>=0&&n<=3):[];}}catch{storageOK=false;}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{storageOK=false;toast('Progress is temporary in this session · التقدم مؤقت في هذه الجلسة');}}
function toast(message){const n=document.getElementById('notice');n.textContent=message;n.style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>n.style.display='none',4500);}
function setLanguage(value){state.language=['en','ar','both'].includes(value)?value:'both';document.documentElement.dataset.language=state.language;document.documentElement.lang=state.language==='en'?'en':'ar';document.querySelectorAll('.languages button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.language===state.language)));save();}
function check(id,en,ar,kind='gate'){const selected=(kind==='gate'?state.gates:state.ready).includes(id);return `<label class="check"><input type="checkbox" data-check="${kind}" data-id="${id}" ${selected?'checked':''}>${label(en,ar)}</label>`;}
function docLink(path,en,ar){return btn(rd(path),en||docs.get(path)?.title||path,ar||docs.get(path)?.title||path);}
function tabs(active=0){return `<div class="tabs">${C.days.map(d=>`<a href="#day-${d.id}" class="${d.id===active?'active':''}">${bi('Day '+d.id,'اليوم '+d.id)}</a>`).join('')}${docLink('docs/04-delivery-plan.md','24-hour plan','خطة 24 ساعة')}</div>`;}
function caution(en,ar){return `<div class="callout warning">${pair(esc(en),esc(ar),'p')}</div>`;}
function note(en,ar){return `<div class="callout">${pair(esc(en),esc(ar),'p')}</div>`;}
function home(){const next=C.days.find(d=>!state.gates.includes(d.id));return `
<section class="hero"><div class="wrap"><p class="kicker">SDAIA ACADEMY · SDA-AIE-211 · SPECIALIST</p>
${pair(`<h1>Turn language into<br><em>understanding.</em></h1><p>Natural Language Processing with Transformers. Build Bayan, one clear step at a time—from a bilingual sentence to an evaluated NLP project.</p><div class="actions">${btn('#start','Start your journey','ابدأ رحلتك','primary')}${btn('#journey','Explore the four days','استكشف الأيام','secondary')}</div>`,`<h1>من نصٍّ نقرؤه،<br>إلى <em>معنى نبنيه.</em></h1><p>معالجة اللغة الطبيعية باستخدام المحولات. نبني «بيان» خطوة واضحة بعد أخرى؛ من جملة عربية وإنجليزية إلى مشروع نقيّمه ونفهم حدوده.</p><div class="actions">${btn('#start','Start your journey','ابدأ رحلتك','primary')}${btn('#journey','Explore the four days','استكشف الأيام','secondary')}</div>`)}
<div class="facts"><div class="fact"><b>04</b><span>Days · أيام</span></div><div class="fact"><b>24</b><span>Learning hours · ساعة تعلم</span></div><div class="fact"><b>05 + 01</b><span>Daily: explanation + lab · شرح + لاب يوميًا</span></div><div class="fact"><b>01</b><span>Cumulative project · مشروع تراكمي</span></div></div>
<div class="pipeline" aria-label="Bayan learning journey"><div class="node">Text<small>النص</small></div><span class="arrow" aria-hidden="true">→</span><div class="node">Tokens<small>وحدات الترميز</small></div><span class="arrow" aria-hidden="true">→</span><div class="node">Transformer<small>المحوّل</small></div><span class="arrow" aria-hidden="true">→</span><div class="node">Tasks & search<small>المهام والبحث</small></div><span class="arrow" aria-hidden="true">→</span><div class="node">Evidence<small>الدليل</small></div></div>
<p class="micro" style="margin-top:22px">Prepared & delivered by Meaad Al-Marri · إعداد وتقديم ميعاد المري</p></div></section>
<div class="wrap"><div class="continue"><div><h2>${bi(next?'Your next step: Day '+next.id:'Your next step: review the project',next?'خطوتك التالية: اليوم '+next.id:'خطوتك التالية: مراجعة المشروع')}</h2><p>${bi('One step, one result, one piece of evidence.','خطوة واحدة، نتيجة مفهومة، ودليل تحفظه.')}</p><div class="progress-track" role="progressbar" aria-label="Personal day progress · تقدم الأيام الشخصي" aria-valuemin="0" aria-valuemax="4" aria-valuenow="${state.gates.length}"><div class="progress-fill" style="width:${state.gates.length*25}%"></div></div><p class="privacy">${bi(`${state.gates.length}/4 self-marked days; not an assessment.`,`${state.gates.length}/4 أيام معلّمة ذاتيًا؛ ليست تقييمًا.`)}</p></div>${btn(next?'#day-'+next.id:'#project','Continue learning','تابع التعلم','primary')}</div>
<section class="section" id="journey">${title('Your four-day journey','رحلتك في أربعة أيام')}<div class="grid">${C.days.map(d=>`<article class="card day-card"><div class="day-top"><span class="day-num">0${d.id}</span><span class="pill">${d.outcomes.join(' · ')}</span></div>${pair(`<h3>${esc(d.label[0])}</h3>`,`<h3>${esc(d.label[1])}</h3>`)}<div class="desc">${pair(`<p>${esc(d.question[0])}</p>`,`<p>${esc(d.question[1])}</p>`)}</div><p class="micro">300 min explanation + 60 min lab<br><span lang="ar" dir="rtl">300 دقيقة شرح + 60 دقيقة لاب</span></p>${btn('#day-'+d.id,'Open Day '+d.id,'افتح اليوم '+d.id,'primary')}${check(d.id,'I completed the day gate','أكملت بوابة اليوم')}</article>`).join('')}</div></section>
<section class="section">${title('A clear way to learn','طريقة تعلّم واضحة')}<div class="grid three"><div class="card"><span class="pill">01 · UNDERSTAND</span>${pair('<h3>Understand before running</h3><p>Start with the question, use the analogy, then read the original lesson.</p>','<h3>افهم قبل التشغيل</h3><p>ابدأ بالسؤال، واستعن بالمثال المبسط، ثم اقرأ الدرس الأصلي.</p>')}</div><div class="card"><span class="pill">02 · BUILD</span>${pair('<h3>Build the same Bayan</h3><p>Seven labs span eight application notebooks, plus one readiness notebook. Lab 3 uses two notebooks.</p>','<h3>ابنِ بيان نفسه</h3><p>سبعة مختبرات عبر ثمانية دفاتر تطبيقية، إضافة إلى دفتر الجاهزية. يستخدم المختبر الثالث دفترين.</p>')}</div><div class="card"><span class="pill">03 · EXPLAIN</span>${pair('<h3>Explain the evidence</h3><p>A saved output is a reference, not your own measured result. Follow the original gate requirements.</p>','<h3>اشرح الدليل</h3><p>المخرج المحفوظ مرجع، وليس نتيجة قياسك أنت. اتبع متطلبات بوابة الإنجاز الأصلية.</p>')}</div></div>
${note('The instructor-requested delivery plan is 24 hours. Learning outcomes, notebooks, datasets and assessment weights are preserved. This is not a new accreditation claim.','خطة التنفيذ المحدّثة بتوجيه المدربة 24 ساعة. الأهداف والدفاتر والبيانات وأوزان التقييم محفوظة؛ ولا يعني تحديث الوقت ادعاء اعتماد جديد.')}
<div class="actions">${docLink('docs/01-outcomes-map.md','Outcomes and evidence','الأهداف وأدلتها')}${docLink('docs/04-delivery-plan.md','Schedule and assessment windows','الجدول ونوافذ التقييم')}${btn('#library','Find a lesson or term','ابحث عن درس أو مصطلح')}</div></section></div>`;}
function dayPage(id){const d=C.days.find(x=>x.id===id);if(!d)return notFound();const slug='day-0'+id;return `<section class="page-top"><div class="wrap"><p class="kicker">DAY 0${id} · ${d.outcomes.join(' / ')} · 6 HOURS</p>${pair(`<h1>${esc(d.label[0])}</h1><p>${esc(d.question[0])}</p>`,`<h1>${esc(d.label[1])}</h1><p>${esc(d.question[1])}</p>`)}</div></section><div class="wrap">${tabs(id)}<section class="section">${pair(`<p>${esc(d.intro[0])}</p>`,`<p>${esc(d.intro[1])}</p>`)}${note(d.analogy[0],d.analogy[1])}${caution(d.watch[0],d.watch[1])}<div class="actions">${docLink(slug+'/README.md','Original day guide','دليل اليوم الأصلي')}${docLink(slug+'/GLOSSARY.md','Glossary + pronunciation','المصطلحات والنطق')}${docLink(slug+'/REFERENCES.md','Primary references','المصادر الأولية')}</div></section>
<section class="section">${title('First, understand · 5 hours','أولًا نفهم · خمس ساعات')}<p class="privacy">${bi('Five 60-minute explanation and demonstration blocks. Breaks are scheduled separately.','خمس فترات شرح وعروض توضيحية، مدة كل منها 60 دقيقة. تنظّم الاستراحات منفصلة.')}</p><div class="schedule">${d.hours.map((h,i)=>`<div class="hour"><div class="hour-id">${i+1}<small>60m</small></div>${label(h[0],h[1])}</div>`).join('')}</div><div class="source-links">${d.lessons.map((p,i)=>`<a href="${rd(p)}">${bi('Lesson '+(i+1),'الدرس '+(i+1))} · ${esc(docs.get(p)?.title||p)}</a>`).join('')}</div></section>
<section class="section"><div class="lab-block">${title('Then, practise · 1 dedicated hour','ثم نطبّق · ساعة مستقلة للّاب')}<p class="privacy">${bi('A planned time budget, not a claim that a clean runtime has been timed. Prepare resources beforehand; retain every Core requirement.','هذا توزيع زمني مستهدف، وليس ادعاء قياس التنفيذ على بيئة نظيفة. جهّز الموارد مسبقًا ولا تُسقط أي متطلب أساسي.')}</p><div class="lab-steps">${d.lab_plan.map(s=>`<div class="lab-step"><b>${s[0]} min<br><span lang="ar">دقيقة</span></b>${label(s[1],s[2])}</div>`).join('')}</div>
<div class="resources">${d.notebooks.map(n=>`<div class="resource"><div><div class="name">Notebook ${esc(n.slice(0,2))}</div><div class="file">${esc(n)}</div></div><div class="actions">${btn(colab(n),'Open in Colab','افتح في كولاب','primary')}${btn(gh('notebooks/'+n),'Saved outputs','المخرجات المحفوظة')}</div></div>`).join('')}</div>
${note('A saved reference result is not a replacement for your execution evidence. Use the documented CPU/recovery route when resources fail.','النتيجة المرجعية المحفوظة لا تستبدل دليل تنفيذك. عند تعطل الموارد استخدم مسار CPU أو الاستعادة الموثق.')}
<div class="actions">${docLink(d.gate,'Gate '+d.gate_name+' requirements','متطلبات البوابة '+d.gate_name)}${docLink('docs/setup/troubleshooting.md','Recover from an error','استعد بعد الخطأ')}</div><h3>${bi('Your evidence today','دليلك اليوم')}</h3>${label(d.evidence[0],d.evidence[1])}${check(d.id,'I checked the original gate and saved my evidence','راجعت البوابة الأصلية وحفظت أدلتي')}</div></section>
<section class="section">${title('Data, not mystery','افهم البيانات التي تعمل عليها')}<div class="resources">${d.datasets.length?d.datasets.map(p=>`<div class="resource"><div class="file">${esc(p)}</div>${btn(gh(p),'Inspect the data','استعرض البيانات')}</div>`).join(''):pair('<p>Use your existing Bayan project artefact and the frozen workload defined in the original Day 4 guide. No new dataset is introduced.</p>','<p>استخدم ناتج مشروع بيان الحالي وعبء العمل المجمد المحدد في دليل اليوم الرابع. لا نضيف مجموعة بيانات جديدة.</p>')}</div>${docLink('data/DATA_CARD.md','Read the data card','اقرأ بطاقة البيانات')}
<details class="quiz"><summary>${bi('Check your understanding · not graded','تحقق من فهمك · دون درجات')}</summary>${label(d.check[0],d.check[1])}<details><summary>${bi('Reveal the explanation','أظهر التفسير')}</summary><div class="answer">${label(d.answer[0],d.answer[1])}</div></details></details>
<div class="actions">${id>1?btn('#day-'+(id-1),'Previous day','اليوم السابق'):btn('#start','Readiness','الجاهزية')}${btn(id<4?'#day-'+(id+1):'#project',id<4?'Next day':'Project and submission',id<4?'اليوم التالي':'المشروع والتسليم','primary')}</div></section></div>`;}
function startPage(){const steps=[['Prepare your Google and GitHub accounts','جهّز حسابي Google وGitHub'],['Check SDA-AIE-112 or equivalent Python/ML foundations','تحقق من SDA-AIE-112 أو ما يعادله في Python وتعلم الآلة'],['Save your notebook copies and run Runtime Doctor','احفظ نسخ دفاترك وشغّل فاحص البيئة'],['Read the data card, privacy rules and project requirements','اقرأ بطاقة البيانات والخصوصية ومتطلبات المشروع']];return `<section class="page-top"><div class="wrap">${pair('<h1>A calm first step.</h1><p>You do not need to know every term yet. Prepare your workspace, follow Core, and keep the recovery guide close.</p>','<h1>بداية هادئة وواضحة.</h1><p>لا تحتاج إلى معرفة كل مصطلح الآن. جهّز مساحة عملك، واتبع المسار الأساسي، واحتفظ بدليل الاستعادة قريبًا.</p>')}</div></section><div class="wrap"><section class="section"><div class="grid two"><div class="card"><h2>${bi('Before Day 1','قبل اليوم الأول')}</h2>${steps.map((s,i)=>check(i,s[0],s[1],'ready')).join('')}<p class="privacy">${bi('These checks are personal reminders, not verified admission or attendance.','هذه علامات تذكير شخصية، وليست تحققًا من القبول أو الحضور.')}</p>${btn(colab('00_runtime_doctor.ipynb'),'Open Runtime Doctor','افتح فاحص البيئة','primary')}</div><div class="card"><h2>${bi('Your minimum setup','تجهيزك الأساسي')}</h2>${pair('<p>Google Colab Free + GitHub. Use the existing CPU fallback; a GPU or paid API is not a course requirement. Follow the original environment instructions.</p>','<p>Google Colab المجاني وGitHub. استخدم بديل CPU الموثق؛ لا يُشترط GPU أو API مدفوع. اتبع تعليمات البيئة الأصلية.</p>')}<div class="actions">${docLink('START_HERE.md','Start-here guide','دليل البداية')}${docLink('docs/setup/README.md','Setup hub','تجهيز البيئة')}${docLink('docs/tools/free-tools.md','Free tools','الأدوات المجانية')}</div></div></div>${note('Use small synthetic course data only. Never publish personal information, credentials or API keys.','استخدم بيانات الدورة الاصطناعية الصغيرة فقط. لا تنشر معلومات شخصية أو ملفات اعتماد أو مفاتيح API.')}<div class="actions">${docLink('docs/policies/integrity-and-privacy.md','Privacy and integrity','الخصوصية والنزاهة')}${docLink('docs/03-capstone-spec.md','Know the final project','تعرّف على المشروع النهائي')}${btn('#day-1','Begin Day 1','ابدأ اليوم الأول','primary')}</div></section></div>`;}
function library(){return `<section class="page-top"><div class="wrap">${pair('<h1>Your learning library.</h1><p>Search the original lessons, glossaries, policies and guides. Source text is preserved; the language switch controls the interface and paired learning summaries.</p>','<h1>مكتبتك التعليمية.</h1><p>ابحث في الدروس والقواميس والسياسات والأدلة الأصلية. النص المرجعي محفوظ بلغته؛ ومفتاح اللغة يغيّر الواجهة والملخصات الثنائية.</p>')}</div></section><div class="wrap"><section class="section"><div class="search-box"><input id="search" type="search" aria-label="Search lessons · ابحث في الدروس" placeholder="Attention, NER, الانتباه، التسليم…" autocomplete="off"><select id="category" aria-label="Filter library · تصفية المكتبة"><option value="">All resources · كل الموارد</option value="day-01/">Day 1 · اليوم الأول</option><option value="day-02/">Day 2 · اليوم الثاني</option><option value="day-03/">Day 3 · اليوم الثالث</option><option value="day-04/">Day 4 · اليوم الرابع</option><option value="GLOSSARY.md">Glossaries · القواميس</option><option value="assessments/">Assessment · التقييم</option><option value="docs/">Guides · الأدلة</option></select></div><p id="search-count" class="privacy" role="status" aria-live="polite"></p><div id="search-results" class="library-list"></div></section></div>`;}
const norm=s=>String(s).toLowerCase().normalize('NFKC').replace(/[\u064B-\u065F\u0670\u0640]/g,'').replace(/[أإآ]/g,'ا');
function updateSearch(){const q=norm(document.getElementById('search').value.trim()),cat=document.getElementById('category').value;let found=DATA.documents.filter(d=>(!cat||d.path.includes(cat))&&(!q||norm(d.search).includes(q)));found.sort((a,b)=>(norm(b.title).includes(q)?1:0)-(norm(a.title).includes(q)?1:0));document.getElementById('search-count').textContent=found.length+' resources · مورد';document.getElementById('search-results').innerHTML=found.length?found.map(d=>`<a href="${rd(d.path)}"><b dir="auto">${esc(d.title)}</b><small>${esc(d.path)}</small></a>`).join(''):`<div class="empty">${label('No match. Try a shorter Arabic or English term.','لا توجد نتيجة. جرّب مصطلحًا أقصر بالعربية أو الإنجليزية.')}</div>`;}
function readPage(path){const d=docs.get(path);if(!d)return notFound();const group=/^day-0([1-4])\//.exec(path);const related=group?DATA.documents.filter(x=>x.path.startsWith('day-0'+group[1]+'/')):DATA.documents.filter(x=>x.path.startsWith('docs/')&&x.path.endsWith('.md')).slice(0,18);return `<div class="wrap">${tabs(group?Number(group[1]):0)}<section class="section"><div class="reader-layout"><aside class="reader-sidebar"><h2>${bi('On this page','في هذه الصفحة')}</h2>${d.headings.slice(0,24).map(h=>`<a class="toc-link" href="${rd(path)}?anchor=${encodeURIComponent(h.id)}" dir="auto">${esc(h.text)}</a>`).join('')}<hr><h2>${bi('Related resources','موارد قريبة')}</h2>${related.map(r=>`<a href="${rd(r.path)}" dir="auto">${esc(r.title)}</a>`).join('')}</aside><article class="reader"><div class="reader-tools">${btn(gh(path),'View the source on GitHub','اعرض المصدر في GitHub')}<button id="print">Print · طباعة</button><button id="font" aria-pressed="false">A+ · تكبير</button>${btn('#library','Library','المكتبة')}</div><div class="source-tag">${esc(path)}<br>${bi('Original reference text. No automatic translation or hidden rewriting.','النص المرجعي الأصلي؛ دون ترجمة آلية أو إعادة كتابة خفية.')}</div><div class="markdown" id="reference-content">${d.html}</div><div class="reading-end">${btn(group?'#day-'+group[1]:'#library','Back to the learning path','العودة لمسار التعلم','primary')}</div></article></div></section></div>`;}
function project(){return `<section class="page-top"><div class="wrap">${pair('<h1>One project. Evidence from every day.</h1><p>Bayan brings together the course you have already studied. The source specification and rubric remain the authority.</p>','<h1>مشروع واحد، ودليل من كل يوم.</h1><p>يجمع بيان ما تعلمته في الدورة نفسها. تظل مواصفات المشروع الأصلية وسُلّم التقييم المرجع الحاكم.</p>')}</div></section><div class="wrap"><section class="section">${title('Assessment stays unchanged','التقييم كما هو دون تغيير')}<div class="score-grid">${[['Labs','المختبرات'],['Practical assessments','التقييمات العملية'],['Quiz','الاختبار'],['Bayan project','مشروع بيان']].map((x,i)=>`<div class="score"><b>${C.assessment_weights[i]}%</b>${label(x[0],x[1])}</div>`).join('')}</div>${note('Six official learning outcomes are integrated in Bayan; the project is not an additional LO7. A single measured project extension is required by R7. Extra distinction tasks remain optional.','يدمج بيان نواتج التعلم الرسمية الستة؛ وليس هدفًا إضافيًا باسم LO7. يظل امتداد المشروع المقاس الواحد إلزاميًا وفق R7، أما مهام التميّز الإضافية فاختيارية.')}
<div class="grid two"><div class="card"><h2>${bi('Before you submit','قبل أن تسلّم')}</h2>${pair('<p>Check the current source checklist: tested notebooks, your actual evidence, README and reports, a valid public repository, the submission validator and the final tag.</p>','<p>راجع القائمة الأصلية: دفاتر مختبرة، أدلتك الفعلية، README وتقارير، مستودع عام صالح، فاحص التسليم، والوسم النهائي.</p>')}<code>submission-v1.0</code><div class="actions">${docLink('docs/policies/submission.md','Submission policy','سياسة التسليم')}${docLink('day-04/05-lab-gates-submission.md','Final gates','البوابات النهائية')}</div></div><div class="card"><h2>${bi('Completion, not just a score','الاجتياز ليس رقمًا فقط')}</h2>${pair('<p>The current policy requires at least 70/100 overall and 70/100 in the project, plus all integrity, evidence and submission conditions. Personal portal checkmarks do not award any score.</p>','<p>تشترط السياسة الحالية 70/100 إجمالًا و70/100 في المشروع على الأقل، مع شروط النزاهة والأدلة والتسليم. علامات التقدم في البوابة لا تمنح درجات.</p>')}<div class="actions">${docLink('docs/policies/assessment-and-completion.md','Full assessment policy','سياسة التقييم كاملة')}${docLink('docs/03-capstone-spec.md','Full Bayan specification','مواصفات بيان كاملة')}</div></div></div>
${caution('The two 30-minute practical assessments, the 15-minute quiz and graded demos need announced organiser-controlled windows. They must not silently replace the 300 minutes of explanation or the 60-minute lab.','يحتاج التقييمان العمليان، 30 دقيقة لكل منهما، والاختبار ذو 15 دقيقة والعروض المقيمة إلى نوافذ معلنة تنظمها الجهة. لا تستبدل بها دقائق الشرح الـ300 أو ساعة اللاب بصمت.')}
<div class="actions">${docLink('assessments/README.md','Assessment materials','مواد التقييم')}${docLink('docs/01-outcomes-map.md','Outcomes-to-evidence map','مصفوفة الأهداف والأدلة')}${btn(C.repository+'/raw/refs/heads/main/downloads/bayan-student-starter.zip','Original student starter ZIP','حزمة بداية الطالب الأصلية')}${docLink('docs/02-verified-runs.md','Recorded run evidence','أدلة التشغيل المسجلة')}</div></section></div>`;}
function help(){return `<section class="page-top"><div class="wrap">${pair('<h1>A problem is a checkpoint, not a dead end.</h1>','<h1>المشكلة نقطة فحص، وليست نهاية الطريق.</h1>')}</div></section><div class="wrap"><section class="section"><div class="grid two"><div class="card"><h2>${bi('Recover your workflow','استعد سير عملك')}</h2>${pair('<p>Save your work, read the first error and follow the source troubleshooting guide. Do not invent outputs or skip Core to look finished.</p>','<p>احفظ عملك، واقرأ أول خطأ، واتبع دليل الأعطال الأصلي. لا تختلق مخرجات أو تتجاوز المتطلبات الأساسية ليبدو العمل مكتملًا.</p>')}<div class="actions">${docLink('docs/setup/troubleshooting.md','Troubleshooting','حل الأعطال')}${docLink('docs/setup/colab.md','Colab guide','دليل كولاب')}${docLink('docs/setup/github.md','GitHub guide','دليل GitHub')}</div></div><div class="card"><h2>${bi('Your personal progress','تقدمك الشخصي')}</h2>${pair('<p>Checkmarks are stored in this browser only. They are not sent to the instructor. Export a personal backup or reset the checkmarks on this device.</p>','<p>تُحفظ العلامات في هذا المتصفح فقط ولا ترسل إلى المدربة. يمكنك تصدير نسخة شخصية أو تصفير العلامات على هذا الجهاز.</p>')}<div class="actions"><button id="export-progress">Export progress · تصدير التقدم</button><button id="reset-progress">Reset progress · تصفير التقدم</button></div><p class="privacy">${storageOK?'Local browser storage · تخزين محلي في المتصفح':'Temporary session only · حفظ مؤقت في الجلسة فقط'}</p></div></div><div class="actions">${docLink('docs/04-delivery-plan.md','Timing and recovery rules','قواعد الوقت والاستعادة')}${docLink('docs/01-outcomes-map.md','What counts as evidence?','ما الذي يُعد دليلًا؟')}${btn('#start','Return to readiness','العودة للجاهزية','primary')}</div></section></div>`;}
function notFound(){return `<div class="wrap"><section class="section"><div class="empty"><h1>Page not found · الصفحة غير موجودة</h1><p>Use the course library to find the original resource.</p><p dir="rtl">استخدم مكتبة الدورة للوصول إلى المورد الأصلي.</p>${btn('#library','Open library','افتح المكتبة','primary')}</div></section></div>`;}
function bindContent(){document.querySelectorAll('[data-check]').forEach(n=>n.addEventListener('change',()=>{const id=Number(n.dataset.id),key=n.dataset.check==='gate'?'gates':'ready';state[key]=n.checked?[...new Set([...state[key],id])]:state[key].filter(x=>x!==id);save();const bar=document.querySelector('[role=progressbar]');if(bar){bar.setAttribute('aria-valuenow',state.gates.length);bar.firstElementChild.style.width=state.gates.length*25+'%';}if(key==='gates'&&['','#home','#journey'].includes(location.hash)){const y=window.scrollY;render();requestAnimationFrame(()=>window.scrollTo(0,y));}toast('Personal progress updated · تم تحديث تقدمك الشخصي');}));
const search=document.getElementById('search');if(search){search.addEventListener('input',updateSearch);document.getElementById('category').addEventListener('change',updateSearch);updateSearch();}
document.getElementById('print')?.addEventListener('click',()=>window.print());document.getElementById('font')?.addEventListener('click',e=>{const on=document.querySelector('.reader').classList.toggle('large');e.currentTarget.setAttribute('aria-pressed',String(on));});
document.querySelectorAll('.markdown pre').forEach(pre=>{const b=document.createElement('button');b.className='copy-code';b.textContent='Copy · نسخ';b.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(pre.querySelector('code')?.textContent||'');toast('Code copied · نُسخ الكود');}catch{toast('Select the code and copy manually · حدد الكود وانسخه يدويًا');}});pre.appendChild(b);});
document.getElementById('export-progress')?.addEventListener('click',()=>{const blob=new Blob([JSON.stringify({course:C.id,version:C.version,saved_at:new Date().toISOString(),...state},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='bayan-personal-progress.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
document.getElementById('reset-progress')?.addEventListener('click',()=>{if(window.confirm('Reset personal progress on this browser? This does not change grades.\nهل تصفّر تقدمك الشخصي في هذا المتصفح؟ لا يتغير أي تقييم.')){state.gates=[];state.ready=[];save();render();toast('Personal progress reset · صُفّر التقدم الشخصي');}});}
function render(){let hash;try{hash=decodeURIComponent(location.hash.slice(1));}catch{hash='invalid';}const [route,params]=hash.split('?');let html;if(!route||route==='home'||route==='journey')html=home();else if(/^day-[1-4]$/.test(route))html=dayPage(Number(route.slice(-1)));else if(route==='start')html=startPage();else if(route==='library')html=library();else if(route==='project')html=project();else if(route==='help')html=help();else if(route.startsWith('read/'))html=readPage(route.slice(5));else html=notFound();document.getElementById('main').innerHTML=html;bindContent();document.title=(route.startsWith('read/')?(docs.get(route.slice(5))?.title||'Bayan'):'بيان | Bayan — Applied NLP')+' · Meaad Al-Marri';const anchor=new URLSearchParams(params||'').get('anchor');requestAnimationFrame(()=>{if(anchor){const target=document.getElementById(anchor);if(target)target.scrollIntoView();else window.scrollTo(0,0);}else if(route==='journey')document.getElementById('journey')?.scrollIntoView();else window.scrollTo(0,0);});}
document.querySelectorAll('.languages button').forEach(b=>b.addEventListener('click',()=>setLanguage(b.dataset.language)));
window.addEventListener('hashchange',()=>{render();document.getElementById('main').focus({preventScroll:true});});
setLanguage(state.language);render();
